# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
from shop import Ui_ShopWindow
from purchases import Ui_PurchasesWindow
from playsound import playsound
import speech_recognition as sr
import pyttsx3
import time
import threading


def speech(main,purchases,shop):
    recognizer = sr.Recognizer()
    microphone = sr.Microphone()
    engine = pyttsx3.init()
    action = 'Listening'
    print(action)
    textToSpeech(engine,action)
    quitFlag = True
    while (quitFlag):
        text = speechToText(recognizer, microphone)
        if not text["success"] and text["error"] == "API unavailable":
            print("ERROR: {}\nclose program".format(text["error"]))
            break;
        while not text["success"]:
            print("I didn't catch that. What did you say?\n")
            text = speechToText(recognizer, microphone)
        if (text["transcription"].lower() == "exit"):
            quitFlag = False
        if (text["transcription"].lower() == "music"):
            main.ToggleSound()
            if(main.isMusic):
                textToSpeech(engine,"Sound enabled")
            else:
                textToSpeech(engine,"Sound disabled")
        print(text["transcription"].lower())
        #self.textToSpeech(engine,text["transcription"].lower())

def speechToText(recognizer, microphone):
    with microphone as source:
        recognizer.adjust_for_ambient_noise(source)
        audio = recognizer.listen(source)
    response = {
    "success": True,
    "error": None,
    "transcription": None
    }
    try:
        response["transcription"] = recognizer.recognize_google(audio)
    except sr.RequestError:
        response["success"] = False
        response["error"] = "API unavailable"
    except sr.UnknownValueError:
        response["success"] = False
        response["error"] = "Unable to recognize speech"
    return response
        
           
def textToSpeech(engine,myText):
    engine.say(myText)
    engine.runAndWait()
    
class Ui_StartingWindow(object):

    
    def openMainMenu(self,id):
        self.ui_list[id].myWindow.hide()
        self.myWindow.show()
    
    def openShop(self):
        self.myWindow.hide()
        if(self.isMusic):
            playsound('sounds\\03 Primary System Sounds\\ui_tap-variant-03.wav',block=False)
        self.ui_list[1].myWindow.show()
        
    def openPurchases(self):
        self.myWindow.hide()
        if(self.isMusic):
            playsound('sounds\\03 Primary System Sounds\\ui_tap-variant-03.wav',block=False)
        self.ui_list[0].myWindow.show()
        
    def ToggleSound(self):
        if(self.isMusic==True):
            self.isMusic=False
            for ui in self.ui_list:
                ui.isMusic=False
            self.pushButton_3.setText("Enable Sound")
        else:
            self.isMusic=True
            for ui in self.ui_list:
                ui.isMusic=True
            self.pushButton_3.setText("Disable Sound")
            
        
        
    def setupUi(self, StartingWindow,ui_list,isMusic):
        
        self.ui_list=ui_list
        
        self.isMusic=isMusic
        theme_file=open("theme.json")
        theme=json.load(theme_file)
        StartingWindow.setObjectName("StartingWindow")
        StartingWindow.resize(831, 643)
        self.myWindow=StartingWindow
        StartingWindow.setObjectName("StartingWindow")
        StartingWindow.resize(831, 643)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StartingWindow.sizePolicy().hasHeightForWidth())
        StartingWindow.setSizePolicy(sizePolicy)
        StartingWindow.setStyleSheet("background-color:"+theme["primary_variant_color"]+";\n"
"color:"+theme["background_color"]+"")
        self.centralwidget = QtWidgets.QWidget(StartingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(-1, 0, 841, 80))
        self.widget_3.setObjectName("widget_3")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setGeometry(QtCore.QRect(0, 0, 831, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color:"+theme["primary_color"]+"")
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget,clicked = lambda:self.ToggleSound())
        self.pushButton_3.setGeometry(QtCore.QRect(30, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{background-color:"+theme["secondary_color"]+";\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: "+theme["secondary_light_variant_color"]+";\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: "+theme["secondary_dark_variant_color"]+";\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(660, -20, 181, 111))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton_3.raise_()
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(0, 560, 841, 81))
        self.widget_4.setStyleSheet("background-color:"+theme["primary_color"]+"")
        self.widget_4.setObjectName("widget_4")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_2.setStyleSheet("opacity:0")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4,clicked = lambda:self.openPurchases())
        self.pushButton_2.setGeometry(QtCore.QRect(450, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{background-color:"+theme["secondary_color"]+";\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: "+theme["secondary_light_variant_color"]+";\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: "+theme["secondary_dark_variant_color"]+";\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_4,clicked = lambda:self.openShop())
        self.pushButton.setGeometry(QtCore.QRect(30, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{background-color:"+theme["secondary_color"]+";\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: "+theme["secondary_light_variant_color"]+";\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: "+theme["secondary_dark_variant_color"]+";\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(-40, 80, 921, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setGeometry(QtCore.QRect(360, 120, 501, 281))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("background_2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_5)
        self.textBrowser.setGeometry(QtCore.QRect(210, -40, 451, 91))
        self.textBrowser.setStyleSheet("border-style: hidden;\n"
"background-color:"+theme["primary_color"]+";\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.textBrowser.setObjectName("textBrowser")
        StartingWindow.setCentralWidget(self.centralwidget)
        self.actionHelp = QtWidgets.QAction(StartingWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionEnglish = QtWidgets.QAction(StartingWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionFrench = QtWidgets.QAction(StartingWindow)
        self.actionFrench.setObjectName("actionFrench")
        self.actionGerman = QtWidgets.QAction(StartingWindow)
        self.actionGerman.setObjectName("actionGerman")

        self.retranslateUi(StartingWindow)
        QtCore.QMetaObject.connectSlotsByName(StartingWindow)

    def retranslateUi(self, StartingWindow):
        _translate = QtCore.QCoreApplication.translate
        StartingWindow.setWindowTitle(_translate("StartingWindow", "MainWindow"))
        if(self.isMusic):
            self.pushButton_3.setText(_translate("StartingWindow", "Disable Sound"))
        else:
            self.pushButton_3.setText(_translate("StartingWindow", "Enable Sound"))
        self.pushButton_2.setText(_translate("StartingWindow", "View purchases"))
        self.pushButton.setText(_translate("StartingWindow", "Begin transaction"))
        self.textBrowser.setHtml(_translate("StartingWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Welcome to the Home Page</span></p></body></html>"))
        self.actionHelp.setText(_translate("StartingWindow", "Help"))
        self.actionEnglish.setText(_translate("StartingWindow", "English"))
        self.actionFrench.setText(_translate("StartingWindow", "French"))
        self.actionGerman.setText(_translate("StartingWindow", "German"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PurchasesWindow = QtWidgets.QMainWindow()
    ui_pw = Ui_PurchasesWindow()
    ui_pw.setupUi(PurchasesWindow,True)
    
    ShopWindow = QtWidgets.QMainWindow()
    ui_sw = Ui_ShopWindow()
    ui_sw.setupUi(ShopWindow,True)
    
    uiList=[ui_pw,ui_sw]
    
    StartingWindow = QtWidgets.QMainWindow()
    ui_mw = Ui_StartingWindow()
    ui_mw.setupUi(StartingWindow,uiList,True)
    
    ui_pw.mainMenuCallback=ui_mw.openMainMenu
    ui_sw.mainMenuCallback=ui_mw.openMainMenu
    
    ui_mw.myWindow.show()
    thread=threading.Thread(target=speech,args=(ui_mw,ui_pw,ui_sw,))
    thread.start()
    

    
    sys.exit(app.exec_())
    
    