# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import os
from playsound import playsound
import speech_recognition as sr
import pyttsx3
import time
import threading

class Ui_ShopWindow(object):


    def BackButton(self):
        if(self.isMusic):
            playsound('sounds\\04 Secondary System Sounds\\navigation_transition-left.wav',block=False)
        self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex()-1)

    def NextButton(self):
        self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex()+1)
       
    def select_car_time(self,car_time):
        if(self.isMusic):
            playsound('sounds\\03 Primary System Sounds\\navigation_forward-selection-minimal.wav',block=False)
        self.car_time=car_time
        self.NextButton()
    
    def select_car_company(self,car_company):
        if(self.isMusic):
            playsound('sounds\\03 Primary System Sounds\\navigation_forward-selection-minimal.wav',block=False)
        self.car_company=car_company
        self.NextButton()  
       
    def select_car_type(self,car_type):
        if(self.isMusic):
            playsound('sounds\\03 Primary System Sounds\\navigation_forward-selection-minimal.wav',block=False)
        self.car_type=car_type
        self.NextButton()
        
    def finishTransaction(self):
        isError=False
        firstname=self.lineEdit.text()
        lastname=self.lineEdit_2.text()
        personalId=self.lineEdit_3.text()
        adress=self.textEdit.toPlainText()
        if(firstname==""):
            isError=True
        if(lastname==""):
            isError=True
        if(personalId==""):
            isError=True
        if(adress==""):
            isError=True
        if(isError==False):
            if(self.isMusic):
                playsound('sounds\\03 Primary System Sounds\\state-change_confirm-up.wav',block=False)
            path="purchases.json"
            theme_file=open(path,"r")
            car={"time":self.car_time,"type":self.car_type,"company":self.car_company,"personal_information":{"firstname":firstname,"lastname":lastname,"personalId":personalId,"adress":adress}}
            if os.stat(path).st_size == 0:
                theme=[]
            else:
                theme=json.load(theme_file)
            theme.append(car)
            theme_file.close()
            theme_file=open(path,"w")
            theme_file.write(json.dumps(theme))
            theme_file.close()
            self.openMainMenu()
        else:
            if(self.isMusic):
                playsound('sounds\\04 Secondary System Sounds\\alert_error-03.wav',block=False)
      
        
    def openMainMenu(self):
        self.change=True
        if(self.isMusic):
            playsound('sounds\\04 Secondary System Sounds\\navigation-cancel.wav',block=False)
        self.mainMenuCallback()

    def setupUi(self, ShopWindow,mainMenuCallback,isMusic):
        self.isMusic=isMusic
        self.mainMenuCallback=mainMenuCallback
        self.car_time=""
        self.car_type=""
        self.car_company=""
        self.information={}
        theme_file=open("theme.json")
        theme=json.load(theme_file)
        ShopWindow.setObjectName("ShopWindow")
        ShopWindow.resize(827, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShopWindow.sizePolicy().hasHeightForWidth())
        ShopWindow.setSizePolicy(sizePolicy)
        ShopWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(ShopWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 831, 641))
        self.stackedWidget.setStyleSheet("color:rgb(0, 0, 0)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_0,clicked = lambda:self.select_car_time("second-hand car"))
        self.pushButton_2.setGeometry(QtCore.QRect(510, 230, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 70%;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_0,clicked = lambda:self.select_car_time("new car"))
        self.pushButton_3.setGeometry(QtCore.QRect(80, 220, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 70%;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_0)
        self.textBrowser.setGeometry(QtCore.QRect(180, 40, 451, 91))
        self.textBrowser.setStyleSheet("border-style: hidden;\n"
"background-color:rgb(137, 83, 243);\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"color:rgb(255, 255, 255)")
        self.textBrowser.setObjectName("textBrowser")
        self.widget_4 = QtWidgets.QWidget(self.page_0)
        self.widget_4.setGeometry(QtCore.QRect(-10, 550, 841, 91))
        self.widget_4.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_4.setObjectName("widget_4")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_2.setStyleSheet("opacity:0")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.page_0)
        self.widget_3.setGeometry(QtCore.QRect(-10, 0, 841, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_3.setObjectName("widget_3")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setGeometry(QtCore.QRect(670, -20, 181, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3,clicked = lambda:self.openMainMenu())
        self.pushButton_5.setGeometry(QtCore.QRect(20, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.widget_4.raise_()
        self.widget_3.raise_()
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_3 = QtWidgets.QLabel(self.page_1)
        self.label_3.mousePressEvent = lambda event: self.select_car_company("BMW")
        self.label_3.setGeometry(QtCore.QRect(310, 220, 221, 111))
        self.label_3.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("car logos/BMW-removebg-preview.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.page_1)
        self.label_2.mousePressEvent = lambda event: self.select_car_company("Audi")
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 221, 111))
        self.label_2.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("car logos/audi-removebg-preview.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.page_1)
        self.label_4.mousePressEvent = lambda event: self.select_car_company("Dacia")
        self.label_4.setGeometry(QtCore.QRect(600, 210, 221, 111))
        self.label_4.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("car logos/Dacia-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_1)
        self.label_5.mousePressEvent = lambda event: self.select_car_company("Hyundai")
        self.label_5.setGeometry(QtCore.QRect(20, 400, 221, 111))
        self.label_5.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("car logos/Hyundai-removebg-preview.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_1)
        self.label_6.mousePressEvent = lambda event: self.select_car_company("Mercedes Benz")
        self.label_6.setGeometry(QtCore.QRect(310, 390, 221, 111))
        self.label_6.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("car logos/mercedes-removebg-preview.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_1)
        self.label_7.mousePressEvent = lambda event: self.select_car_company("Volkswagen")
        self.label_7.setGeometry(QtCore.QRect(590, 390, 221, 111))
        self.label_7.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("car logos/Volkswagen-removebg-preview.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_1)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 40, 451, 91))
        self.textBrowser_2.setStyleSheet("border-style: hidden;\n"
"background-color:rgb(137, 83, 243);\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"color:rgb(255, 255, 255)")
        self.textBrowser_2.setObjectName("textBrowser_2")
        
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        
        self.widget_9 = QtWidgets.QWidget(self.page_1)
        self.widget_9.setGeometry(QtCore.QRect(0, 0, 841, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_9.setObjectName("widget_9")
        self.label_23 = QtWidgets.QLabel(self.widget_9)
        self.label_23.setGeometry(QtCore.QRect(660, -20, 181, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_9,clicked = lambda:self.BackButton())
        self.pushButton_9.setGeometry(QtCore.QRect(10, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_9,clicked = lambda:self.openMainMenu())
        self.pushButton_16.setGeometry(QtCore.QRect(160, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.widget_13 = QtWidgets.QWidget(self.widget_9)
        self.widget_13.setGeometry(QtCore.QRect(-10, 550, 841, 91))
        self.widget_13.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_13.setObjectName("widget_13")
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        self.widget_14.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_14.setStyleSheet("opacity:0")
        self.widget_14.setObjectName("widget_14")
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.widget_10 = QtWidgets.QWidget(self.page_1)
        self.widget_10.setGeometry(QtCore.QRect(-10, 550, 841, 91))
        self.widget_10.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        self.widget_11.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_11.setStyleSheet("opacity:0")
        self.widget_11.setObjectName("widget_11")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.mousePressEvent = lambda event: self.select_car_type("Compact")
        self.label_9.setGeometry(QtCore.QRect(100, 240, 221, 111))
        self.label_9.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("car types/Compact-removebg-preview.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.mousePressEvent = lambda event: self.select_car_type("SUV")
        self.label_10.setGeometry(QtCore.QRect(510, 230, 221, 111))
        self.label_10.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("car types/SUV-removebg-preview.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.mousePressEvent = lambda event: self.select_car_type("Mid-size")
        self.label_11.setGeometry(QtCore.QRect(110, 440, 221, 111))
        self.label_11.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("car types/Mid-size-removebg-preview.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.mousePressEvent = lambda event: self.select_car_type("Cabriolet")
        self.label_12.setGeometry(QtCore.QRect(520, 440, 221, 111))
        self.label_12.setStyleSheet("QLabel:hover{\n"
"background-color:rgb(227, 131, 246);\n"
"}\n"
"QLabel:pressed{\n"
"background-color:rgb(96, 9, 113);\n"
"}")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("car types/Cabriolet-removebg-preview.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.widget_8 = QtWidgets.QWidget(self.page_2)
        self.widget_8.setGeometry(QtCore.QRect(-10, 550, 841, 91))
        self.widget_8.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_8.setObjectName("widget_8")
        self.widget_15 = QtWidgets.QWidget(self.widget_8)
        self.widget_15.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_15.setStyleSheet("opacity:0")
        self.widget_15.setObjectName("widget_15")
        self.widget_16 = QtWidgets.QWidget(self.page_2)
        self.widget_16.setGeometry(QtCore.QRect(0, 0, 841, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_16.setObjectName("widget_16")
        self.label_22 = QtWidgets.QLabel(self.widget_16)
        self.label_22.setGeometry(QtCore.QRect(660, -20, 181, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_16,clicked = lambda:self.BackButton())
        self.pushButton_11.setGeometry(QtCore.QRect(10, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_16,clicked = lambda:self.openMainMenu())
        self.pushButton_21.setGeometry(QtCore.QRect(160, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(180, 40, 451, 91))
        self.textBrowser_3.setStyleSheet("border-style: hidden;\n"
"background-color:rgb(137, 83, 243);\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"color:rgb(255, 255, 255);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_3.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.widget_8.raise_()
        self.widget_16.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setGeometry(QtCore.QRect(420, 140, 391, 391))
        self.widget.setStyleSheet("background-color:rgb(227, 131, 246);\n"
"color:rgb(0, 0, 0);\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(50, 20, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 210, 211, 31))
        self.lineEdit_6.setStyleSheet("QLineEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QLineEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 160, 211, 31))
        self.lineEdit_4.setStyleSheet("QLineEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QLineEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setGeometry(QtCore.QRect(10, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 110, 211, 31))
        self.lineEdit_5.setStyleSheet("QLineEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QLineEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(10, 210, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setGeometry(QtCore.QRect(10, 260, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 260, 211, 31))
        self.lineEdit_7.setStyleSheet("QLineEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QLineEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setGeometry(QtCore.QRect(90, 330, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setGeometry(QtCore.QRect(170, 330, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.widget_5 = QtWidgets.QWidget(self.page_3)
        self.widget_5.setGeometry(QtCore.QRect(10, 140, 391, 391))
        self.widget_5.setStyleSheet("background-color:rgb(227, 131, 246);\n"
"color:rgb(0, 0, 0);\n"
"border-radius:10px;")
        self.widget_5.setObjectName("widget_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit.setGeometry(QtCore.QRect(170, 130, 211, 31))
        self.lineEdit.setStyleSheet("QLineEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QLineEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 180, 211, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QLineEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 230, 211, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QLineEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setGeometry(QtCore.QRect(30, 130, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setGeometry(QtCore.QRect(30, 180, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setGeometry(QtCore.QRect(30, 230, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setGeometry(QtCore.QRect(30, 300, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.textEdit = QtWidgets.QTextEdit(self.widget_5)
        self.textEdit.setGeometry(QtCore.QRect(170, 280, 211, 101))
        self.textEdit.setStyleSheet("QTextEdit{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(0, 0, 0);\n"
"border-width:1px\n"
"}\n"
"QTextEdit:focus{color:rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:1px\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        self.label_16.setGeometry(QtCore.QRect(50, 20, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.widget_21 = QtWidgets.QWidget(self.page_3)
        self.widget_21.setGeometry(QtCore.QRect(280, 740, 841, 91))
        self.widget_21.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_21.setObjectName("widget_21")
        self.widget_22 = QtWidgets.QWidget(self.widget_21)
        self.widget_22.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_22.setStyleSheet("opacity:0")
        self.widget_22.setObjectName("widget_22")
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.widget_27 = QtWidgets.QWidget(self.page_3)
        self.widget_27.setGeometry(QtCore.QRect(-10, 550, 841, 91))
        self.widget_27.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_27.setObjectName("widget_27")
        self.widget_28 = QtWidgets.QWidget(self.widget_27)
        self.widget_28.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_28.setStyleSheet("opacity:0")
        self.widget_28.setObjectName("widget_28")
        self.pushButton_23 = QtWidgets.QPushButton(self.widget_27,clicked = lambda:self.finishTransaction())
        self.pushButton_23.setGeometry(QtCore.QRect(230, 20, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.widget_29 = QtWidgets.QWidget(self.page_3)
        self.widget_29.setGeometry(QtCore.QRect(-10, 0, 841, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_29.sizePolicy().hasHeightForWidth())
        self.widget_29.setSizePolicy(sizePolicy)
        self.widget_29.setStyleSheet("background-color:rgb(137, 83, 243)")
        self.widget_29.setObjectName("widget_29")
        self.label_32 = QtWidgets.QLabel(self.widget_29)
        self.label_32.setGeometry(QtCore.QRect(670, -20, 181, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.pushButton_24 = QtWidgets.QPushButton(self.widget_29,clicked = lambda:self.BackButton())
        self.pushButton_24.setGeometry(QtCore.QRect(20, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_29,clicked = lambda:self.openMainMenu())
        self.pushButton_22.setGeometry(QtCore.QRect(170, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton{background-color:rgb(177, 15, 210);\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"    background-color: rgb(227, 131, 246);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 9, 114);\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_4.setGeometry(QtCore.QRect(180, 40, 451, 91))
        self.textBrowser_4.setStyleSheet("border-style: hidden;\n"
"background-color:rgb(137, 83, 243);\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"color:rgb(255, 255, 255)")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_4.raise_()
        self.widget.raise_()
        self.widget_5.raise_()
        self.widget_21.raise_()
        self.widget_27.raise_()
        self.widget_29.raise_()
        self.stackedWidget.addWidget(self.page_3)
        ShopWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShopWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ShopWindow)

    def retranslateUi(self, ShopWindow):
        _translate = QtCore.QCoreApplication.translate
        ShopWindow.setWindowTitle(_translate("ShopWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("ShopWindow", "Second Hand Car"))
        
        self.pushButton_3.setText(_translate("ShopWindow", "New Car"))
        self.textBrowser.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">New car or Old car</span></p></body></html>"))
        self.pushButton_5.setText(_translate("ShopWindow", "Main Menu"))
        self.textBrowser_2.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Choose the car company</span></p></body></html>"))

        self.pushButton_9.setText(_translate("ShopWindow", "Back"))
        self.pushButton_16.setText(_translate("ShopWindow", "Main Menu"))
        self.pushButton_11.setText(_translate("ShopWindow", "Back"))
        self.pushButton_21.setText(_translate("ShopWindow", "Main Menu"))
        self.textBrowser_3.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Choose the car type</span></p></body></html>"))
        self.label_17.setText(_translate("ShopWindow", "Payment information"))
        self.label_19.setText(_translate("ShopWindow", "Card number"))
        self.label_20.setText(_translate("ShopWindow", "Name on card"))
        self.label_18.setText(_translate("ShopWindow", "Expiry date"))
        self.label_21.setText(_translate("ShopWindow", "Security code"))
        self.label_27.setText(_translate("ShopWindow", "Price:"))
        self.label_28.setText(_translate("ShopWindow", "car_price"))
        self.label.setText(_translate("ShopWindow", "Firstname"))
        self.label_8.setText(_translate("ShopWindow", "Lastname"))
        self.label_14.setText(_translate("ShopWindow", "Personal ID"))
        self.label_15.setText(_translate("ShopWindow", "Adress"))
        self.label_16.setText(_translate("ShopWindow", "Personal information"))
        self.pushButton_23.setText(_translate("ShopWindow", "Finish Transaction"))
        self.pushButton_24.setText(_translate("ShopWindow", "Back"))
        self.pushButton_22.setText(_translate("ShopWindow", "Main Menu"))
        self.textBrowser_4.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Insert your informations</span></p></body></html>"))
