# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_ShopWindow(object):
    def setupUi(self, ShopWindow):
        theme_file=open("theme.json")
        theme=json.load(theme_file)
        ShopWindow.setObjectName("ShopWindow")
        ShopWindow.resize(826, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShopWindow.sizePolicy().hasHeightForWidth())
        ShopWindow.setSizePolicy(sizePolicy)
        ShopWindow.setStyleSheet("background-color:"+theme["on_primary_color"]+"")
        self.centralwidget = QtWidgets.QWidget(ShopWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 821, 471))
        self.stackedWidget.setStyleSheet("color:"+theme["on_background_color"]+"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 140, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:"+theme["secondary_color"]+";\n"
"color:"+theme["on_primary_color"]+";\n"
"border: 2px solid #555;\n"
"border-radius: 70%;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 140, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:"+theme["secondary_color"]+";\n"
"color:"+theme["on_primary_color"]+";\n"
"border: 2px solid #555;\n"
"border-radius: 70%;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser.setGeometry(QtCore.QRect(180, -30, 451, 91))
        self.textBrowser.setStyleSheet("border-style: hidden;\n"
"background-color:"+theme["primary_color"]+";\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(310, 110, 221, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("car logos/BMW.PNG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 221, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("car logos/audi.PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(600, 100, 221, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("car logos/Dacia.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 221, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("car logos/Hyundai.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(310, 280, 221, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("car logos/mercedes.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(590, 280, 221, 111))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("car logos/Volkswagen.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, -30, 451, 91))
        self.textBrowser_2.setStyleSheet("border-style: hidden;\n"
"background-color:"+theme["primary_color"]+";\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(100, 120, 221, 111))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("car types/Compact.PNG"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(510, 110, 221, 111))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("car types/SUV.PNG"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(110, 320, 221, 111))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("car types/Mid-size.PNG"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(520, 320, 221, 111))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("car types/Cabriolet.PNG"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(180, -30, 451, 91))
        self.textBrowser_3.setStyleSheet("border-style: hidden;\n"
"background-color:"+theme["primary_color"]+";\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_4.setGeometry(QtCore.QRect(180, -40, 451, 91))
        self.textBrowser_4.setStyleSheet("border-style: hidden;\n"
"background-color:"+theme["primary_color"]+";\n"
"border-radius: 40px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"color:"+theme["on_primary_color"]+"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.widget = QtWidgets.QWidget(self.page_4)
        self.widget.setGeometry(QtCore.QRect(420, 60, 391, 391))
        self.widget.setStyleSheet("background-color:"+theme["secondary_variant_color"]+";\n"
"color:"+theme["on_primary_color"]+";\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(50, 20, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 210, 211, 31))
        self.lineEdit_6.setStyleSheet("color:"+theme["on_primary_color"]+";\n"
"border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 160, 211, 31))
        self.lineEdit_4.setStyleSheet("border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px;\n"
"color:"+theme["on_primary_color"]+";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setGeometry(QtCore.QRect(10, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 110, 211, 31))
        self.lineEdit_5.setStyleSheet("color:"+theme["on_primary_color"]+";\n"
"border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(10, 210, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setGeometry(QtCore.QRect(10, 260, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 260, 211, 31))
        self.lineEdit_7.setStyleSheet("color:"+theme["on_primary_color"]+";\n"
"border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setGeometry(QtCore.QRect(90, 330, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setGeometry(QtCore.QRect(170, 330, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.widget_5 = QtWidgets.QWidget(self.page_4)
        self.widget_5.setGeometry(QtCore.QRect(10, 60, 391, 391))
        self.widget_5.setStyleSheet("background-color:"+theme["secondary_variant_color"]+";\n"
"color:"+theme["on_primary_color"]+";\n"
"border-radius:10px;")
        self.widget_5.setObjectName("widget_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit.setGeometry(QtCore.QRect(170, 130, 211, 31))
        self.lineEdit.setStyleSheet("color:"+theme["on_primary_color"]+";\n"
"border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 180, 211, 31))
        self.lineEdit_2.setStyleSheet("border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px;\n"
"color:"+theme["on_primary_color"]+";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 230, 211, 31))
        self.lineEdit_3.setStyleSheet("color:"+theme["on_primary_color"]+";\n"
"border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setGeometry(QtCore.QRect(30, 130, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setGeometry(QtCore.QRect(30, 180, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setGeometry(QtCore.QRect(30, 230, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setGeometry(QtCore.QRect(30, 300, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.textEdit = QtWidgets.QTextEdit(self.widget_5)
        self.textEdit.setGeometry(QtCore.QRect(170, 280, 211, 101))
        self.textEdit.setStyleSheet("border-style:solid;\n"
"border-color:"+theme["on_primary_color"]+";\n"
"border-width:1px")
        self.textEdit.setObjectName("textEdit")
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        self.label_16.setGeometry(QtCore.QRect(50, 20, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.widget.raise_()
        self.widget_5.raise_()
        self.textBrowser_4.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 841, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("background-color:"+theme["primary_color"]+"")
        self.widget_3.setObjectName("widget_3")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setGeometry(QtCore.QRect(660, -20, 181, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color:"+theme["secondary_color"]+";\n"
"color:"+theme["on_primary_color"]+";\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(-10, 550, 841, 91))
        self.widget_4.setStyleSheet("background-color:"+theme["primary_color"]+"")
        self.widget_4.setObjectName("widget_4")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setGeometry(QtCore.QRect(20, 350, 811, 80))
        self.widget_2.setStyleSheet("opacity:0")
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setGeometry(QtCore.QRect(230, 20, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:"+theme["secondary_color"]+";\n"
"color:"+theme["on_primary_color"]+";\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"padding: 5px;")
        self.pushButton.setObjectName("pushButton")
        ShopWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShopWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ShopWindow)

    def retranslateUi(self, ShopWindow):
        _translate = QtCore.QCoreApplication.translate
        ShopWindow.setWindowTitle(_translate("ShopWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("ShopWindow", "Second Hand Car"))
        self.pushButton_3.setText(_translate("ShopWindow", "New Car"))
        self.textBrowser.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">New car or Old car</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Choose the car company</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Choose the car type</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("ShopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Insert your informations</span></p></body></html>"))
        self.label_17.setText(_translate("ShopWindow", "Payment information"))
        self.label_19.setText(_translate("ShopWindow", "Card number"))
        self.label_20.setText(_translate("ShopWindow", "Name on card"))
        self.label_18.setText(_translate("ShopWindow", "Expiry date"))
        self.label_21.setText(_translate("ShopWindow", "Security code"))
        self.label_27.setText(_translate("ShopWindow", "Price:"))
        self.label_28.setText(_translate("ShopWindow", "car_price"))
        self.label.setText(_translate("ShopWindow", "Firstname"))
        self.label_8.setText(_translate("ShopWindow", "Lastname"))
        self.label_14.setText(_translate("ShopWindow", "Personal ID"))
        self.label_15.setText(_translate("ShopWindow", "Adress"))
        self.label_16.setText(_translate("ShopWindow", "Personal information"))
        self.pushButton_5.setText(_translate("ShopWindow", "Main Menu"))
        self.pushButton.setText(_translate("ShopWindow", "Finish Transaction"))


